In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import matplotlib as mpl
import pandas as pd

In [5]:
np.load("Datasets/dataset_A.npz").files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [4]:
datasets = [np.load("Datasets/dataset_A.npz"), np.load("Datasets/dataset_B.npz"), np.load("Datasets/dataset_C.npz"), np.load("Datasets/dataset_D.npz")]
datasets[0].files
datasets[0]['arr_0']

array([[-0.72530338,  0.82268144],
       [ 0.02619935,  0.20195171],
       [ 0.68680741,  0.40459509],
       ...,
       [ 0.53226229, -0.35801377],
       [ 0.6113741 , -0.5773362 ],
       [ 0.3991032 , -0.21454145]])

In [8]:
arr = np.array([
    np.array([1, 2, 3]),
    np.array([4, 5, 6]),
    np.array([7, 8, 9])
])
arr[:,1]

array([2, 5, 8])

In [10]:
np.dot(np.transpose(np.array([1, 2, 3])), np.array([1, 2, 3]))

14

In [5]:
X = np.array([
    np.array([1, 2, 3]),
    np.array([4, 5, 6]),
    np.array([7, 8, 9]),
    np.array([10, 11, 12]),
    np.array([13, 14, 15]),
    np.array([16, 17, 18]),
    np.array([19, 20, 21]),
    np.array([22, 23, 24]),
    np.array([25, 26, 27]),
    np.array([28, 29, 30])
])
np.append(X[1:3], X[7:], axis=0)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [7]:
X[:4]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
5.1%3

2.0999999999999996

In [12]:
5.1 - 3*(5.1//3)

2.0999999999999996

In [13]:
5.1 - 3*5.1//3

0.09999999999999964

In [25]:
svclf = svm.SVC()
gamma=0.5
svclf.set_params(**{'gamma':gamma, 'degree':5})
svclf.gamma

0.5

In [24]:
svclf.degree

5

In [51]:
np.unique(datasets[0]['arr_0'][:,0]).shape
# datasets[0]['arr_0'].shape

(1500,)

In [2]:
def learn_SVM(X, Y, kernel='linear', reg_param=0., kernel_param=1.):
    """
    Makes an svm.SVC object, fits it to X, Y, and returns the object
    """
    svm_clf = svm.SVC(C=reg_param, kernel=kernel, coef0=1)
    if kernel == 'rbf':
        svm_clf.set_params(**{'gamma':kernel_param})
    elif kernel == 'poly':
        svm_clf.set_params(**{'degree':kernel_param, 'gamma':1})
    svm_clf.fit(X, Y)
    return svm_clf

In [9]:
saved_svm = learn_SVM(datasets[0]['arr_0'], datasets[0]['arr_1'], 'linear', 1e-3, 1e1)
print(saved_svm.coef0)
print(saved_svm.C)
print(saved_svm.kernel)
print(saved_svm.gamma)
print(saved_svm.degree)

1
0.001
linear
scale
3


In [11]:
datasets[3]['arr_0'].shape

(400, 30)

In [16]:
np.max(datasets[2]['arr_0'])

16.0

In [20]:
dict = {
    'sample1': 46,
    'sample2': 643,
    'sample3': 'heks',
    'random' : 2.3
}
dict['sample2']

643

In [25]:
X = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]]
X_sub = list(x for x in X if x[1] >= 5)
X_sub

[[4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [36]:
X = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]]
Y = [40, 10, 32, 43]
Y_sub = list(Y[i] for i,x in enumerate(X) if x[1] >= 5)
Y_sub

<function list.count(value, /)>

In [27]:
np.size([1, 2, 3])

3

In [28]:
np.size((4, 3, False))

3

In [31]:
lst = [3, 3, 2, 4, 2, 3, 2]
max(set(lst), key=lst.count)

2

In [35]:
np.size(np.unique(lst)) == 1

False

In [38]:
x = 5
y = x
y = y + 2
x

5

In [43]:
lst = np.array(list(x for x in [[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
lst

array(<generator object <genexpr> at 0x7f16813473e0>, dtype=object)

In [44]:
np.log2(4)

2.0

In [12]:
Y = [1, 2, 3, 1, 4, 3, 2]
list(y for y in Y if y==1)

[1, 1]

In [18]:
def accuracy_score(Y_true, Y_pred):
    return np.size(Y_true[Y_true==Y_pred])/np.size(Y_true)

accuracy_score(np.array([1, 3, 2]), np.array([1, 2, 2]))
# Y_true = np.array([1, 3, 2])
# Y_pred = np.array([1, 2, 2])
# np.size(Y_pred[Y_true==Y_pred])

0.6666666666666666

In [19]:
Y = np.array([1, 3, 2, 4, 1])
Y[Y==1].shape

(2,)

In [20]:
np.sum([1, 2, 3])

6

In [3]:
np.zeros((4,3)).tolist()

[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

In [4]:
l1 = np.array([
    [0, 1],
    [-1, 4],
    [1, 3],
    [4, 2]
])
l2 = l1.copy()

In [6]:
np.unique(l2[:,0])

array([-1,  0,  1,  4])

In [7]:
l2[l2[:,0].argsort()]

array([[-1,  4],
       [ 0,  1],
       [ 1,  3],
       [ 4,  2]])

In [8]:
l2

array([[ 0,  1],
       [-1,  4],
       [ 1,  3],
       [ 4,  2]])

In [10]:
l3 = np.array([1, 2, 3, 4])
l3[l2[:,1].argsort()]

array([1, 4, 3, 2])

In [16]:
X_real = np.load("Datasets/dataset_A.npz")['arr_0']
X_real[X_real[:,0].argsort()].shape

(1500, 2)

In [25]:
i = 0
dataset = np.load("Datasets/dataset_A.npz")
X = dataset['arr_0']
Y = dataset['arr_1']
choices = np.unique(X[:,i])
left_pts = 0
right_pts = X.shape[0]
left_pos_pts = 0
right_pos_pts = np.size(Y[Y==1])
next_index = 0
X_sort = X[X[:,i].argsort()]
Y_sort = Y[X[:,i].argsort()]
for choice in choices:
     while (next_index < X.shape[0] and X_sort[next_index, i] == choice):
        left_pts = left_pts + 1
        right_pts = right_pts - 1
        if Y_sort[next_index] == 1:
            left_pos_pts = left_pos_pts + 1
            right_pos_pts = right_pos_pts -1
        next_index = next_index + 1

In [28]:
dataset = np.load("Datasets/dataset_A.npz")
X = dataset['arr_0']
Y = dataset['arr_1']
choices = np.unique(X[:,i])
left_pts = 0
right_pts = X.shape[0]
left_pos_pts = 0
right_pos_pts = np.size(Y[Y==1])
for choice in choices:
    Y_curr = np.array(list(Y[j] for j,x in enumerate(X) if x[i] == choice))
    left_pts = left_pts + np.size(Y_curr)
    right_pts = right_pts - np.size(Y_curr)
    left_pos_pts = left_pos_pts + np.size(Y_curr[Y_curr==1])
    right_pos_pts = right_pos_pts - np.size(Y_curr[Y_curr==1])

In [32]:
Y = np.array([1, -1, 1, 1, -1, -1, -1])
Y[Y==1].shape[0] >= Y[Y==-1].shape[0]
np.size(Y[Y==1])

3

In [35]:
np.max([2, 3])

3

In [36]:
np.log2(0)

/tmp/ipykernel_6767/2251961259.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(0)


-inf

In [37]:
0 * np.log2(0)

/tmp/ipykernel_6767/1076561811.py:1: RuntimeWarning: divide by zero encountered in log2
  0 * np.log2(0)
/tmp/ipykernel_6767/1076561811.py:1: RuntimeWarning: invalid value encountered in double_scalars
  0 * np.log2(0)


nan

In [42]:
X = np.array([1, 2, 3])
Y = np.array([1, 4, 3])
(X == Y).all()

False

In [49]:
X = np.array([
    np.array([1, 2, 3]),
    np.array([2, 3, 4]),
    np.array([3, 4, 5]),
    np.array([4, 5, 6])
])
print(X)
print(X[1:])
Y = np.array(list(x for x in X if x[1] > 3))
print(Y)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]


In [60]:
X = np.array([
    np.array([1, 2, 3]),
    np.array([2, 3, 4]),
    np.array([3, 4, 5]),
    np.array([4, 5, 6])
])
for x in X:
    print(type(x))
Y = np.array([
    np.array([7, 2, 3]),
    np.array([2, 3, 4]),
    np.array([3, 4, 5]),
    np.array([4, 5, 6])
])
Z = np.array([
    np.array([1, 2, 3]),
    np.array([2, 3, 4]),
    np.array([3, 4, 5]),
    np.array([4, 5, 6])
])
print(type(Z))
if (X == Y).all() or (X == Z).all():
    print("Yay")
else:
    print("Noo")
X.shape == Y.shape

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Yay


True

In [65]:
np.array(range(1,41)).shape

(40,)

In [73]:
l1 = []
l1.append(3)
l1

[3]

In [74]:
int(0.5 * 5)

2

In [81]:
X = np.array([
    np.array([1, 2, 3]),
    np.array([2, 3, 4]),
    np.array([3, 4, 5]),
    np.array([4, 5, 6])
])
a = 0.5
X_new = np.array(list(X[np.random.randint(0, X.shape[0])] for j in range(int(a*X.shape[0]))))
X_new

array([[2, 3, 4],
       [1, 2, 3]])

In [91]:
X = np.array([
    np.array([1, 2, 3, 4]),
    np.array([2, 3, 4, 5]),
    np.array([3, 4, 5, 6]),
    np.array([4, 5, 6, 7])
])
b = 0.5
rng = np.random.default_rng()
random_features = rng.permutation(X.shape[1])[:int(b*X.shape[1])]
random_features

array([3, 1])

In [93]:
for i in range(3):
    print("oops")

oops
oops
oops


In [94]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])

In [99]:
np.array([2, 3, 5]) ** np.array([1, 2, 3])

array([  2,   9, 125])

In [101]:
np.size([1, 2, 3])

3

In [9]:
np.sum(np.load("Datasets/dataset_D.npz")['arr_1'])

54.0

In [10]:
0**0

1

In [12]:
1 - np.array([1, 0, 1, 0, 0])

array([0, 1, 0, 1, 1])

In [14]:
1 != 2

True

In [15]:
np.log(np.inf)

inf

In [18]:
np.inf * 2 + 1 * 3 >= 0 

True

In [20]:
np.sum(np.array(list([np.inf, 1, 3, np.inf])))

inf

In [23]:
gamma = 0.5
(0.5 + gamma)/(0.5 - gamma)

ZeroDivisionError: float division by zero

In [26]:
Y = np.array([1, -1, 1, -1, -1])
w = np.array([3, 2, 2, 1, 3])
np.sum(w[Y==1]) >= np.sum(w[Y==-1])

False

In [30]:
l = np.array([0, 1, 1, 0, 1, 0, 0])
w = np.ones(l.shape)
gamma = 0.5 - np.sum(w * l)/np.sum(w)
beta = (0.5 + gamma)/(0.5 - gamma)
w = w * (beta ** l)
print(gamma)
print(beta)
print(w)

0.07142857142857145
1.3333333333333333
[1.         1.33333333 1.33333333 1.         1.33333333 1.
 1.        ]


In [31]:
x = -1
y = 1
np.abs(x - y)/2

1.0

In [32]:
np.logspace(-4, 3, num=8, base=10)

array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

In [36]:
X_test = np.load("Datasets/dataset_D.npz")['arr_0']
np.max(X_test)

3432.0

In [37]:
-np.inf

-inf

In [38]:
class CustomScaler:
    def __init__(self, low, high):
        self.low = low
        self.high = high
    
    def scale(self, x):
        return (x - self.low)/(self.high - self.low)

X = np.array([
    np.array([1, 2, 3]),
    np.array([0, -1, 3]),
    np.array([0, 2, 4])
])

scaler = CustomScaler(np.min(X), np.max(X))
scaler.scale(X)

array([[0.4, 0.6, 0.8],
       [0.2, 0. , 0.8],
       [0.2, 0.6, 1. ]])

In [40]:
Y = np.array([1, -1, -1, 1, 1])
np.sum(Y == 1)

0

In [47]:
X = np.array([
    np.array([1, 2, 3]),
    np.array([2, 3, 1]),
    np.array([3, 4, 1])
])
X_norm = np.sum(X**2, axis=-1)
X_norm[None,:]

array([[14, 14, 26]])

In [113]:
def linear_kernel_value(u, v):
    return np.dot(u, v)

def poly_kernel_value(u, v, d):
    return (1+np.dot(u, v))**d

# def rbf_kernel_value(u, v, gamma):
#     return np.exp(-1*gamma*(np.dot(np.subtract(u, v).T, np.subtract(u, v))))

def rbf_kernel_value(u, v, gamma):
    return np.exp(gamma*(2*np.matmul(u.T, v) - np.matmul(u.T, u) - np.matmul(v.T, v)))

def rbf_kernel_value_maybe(u, v, gamma):
    # const_term = np.exp(-1*np.matmul(u.T, u))
    return np.exp(-1*np.matmul(u.T, u)) * np.matmul(
        np.transpose(np.exp(2*np.matmul(u.T, v))),
        np.exp(np.sum(v**2, axis=0))
    )

# def get_kernel_value(u, v, kernel, kernel_param):
#     if kernel == 'linear':
#         return linear_kernel_value(u, v)
#     elif kernel == 'rbf':
#         return rbf_kernel_value(u, v, kernel_param)
#     elif kernel == 'poly':
#         return poly_kernel_value(u, v, kernel_param)

def get_kernel_value(u, v, kernel, kernel_param):
    if kernel == 'linear':
        return linear_kernel_value(u, v)
    elif kernel == 'rbf':
        return rbf_kernel_value(u, v, kernel_param)
    elif kernel == 'poly':
        return poly_kernel_value(u, v, kernel_param)

def get_kernel_values(U, V, kernel, kernel_param):
    return np.array(list(np.array(list(get_kernel_value(u, v, kernel, kernel_param) for v in V)) for u in U))

def get_kernel_values_maybe(U, V, kernel, kernel_param):
    if kernel == 'rbf':
        return np.exp(-1*kernel_param*(
            # np.add(np.matmul(U.T, U), 
            np.add(np.sum(U**2, axis=0),
            np.add(-2*np.matmul(U.T, V), np.sum(V**2, axis=0)))
        ))
    else:
        return get_kernel_value(U, V, kernel, kernel_param)

# def get_kernel_matrix(X, kernel, kernel_param):
#     return np.array(list(np.array(list(get_kernel_value(X_i, X_j, kernel, kernel_param) for X_j in X)) for X_i in X))

def get_kernel_matrix(X, kernel, kernel_param):
    return np.array(list(np.array(list(get_kernel_value(X_i, X_j, kernel, kernel_param) for X_j in X)) for X_i in X))

def get_kernel_matrix_maybe(X, kernel, kernel_param):
    # return get_kernel_value(X, np.transpose(X), kernel, kernel_param)
    if kernel == 'linear':
        return np.matmul(X, np.transpose(X))
    elif kernel == 'poly':
        return (1 + np.matmul(X, np.transpose(X)))**kernel_param
    elif kernel == 'rbf':
        X_norm_sq = np.sum(X**2, axis=1)
        return np.exp(-1 * kernel_param * (X_norm_sq[:, None] + X_norm_sq[None, :]- 2*np.matmul(X, np.transpose(X))))

X = np.array([
    np.array([1, 2, 3, 1]),
    np.array([3, 2, 5, 0]),
    np.array([3, 1, 4, 4])
    # np.array([4, 2, 5])
])

x = np.array([1, 4, 3, 0])
y = np.array([3, 2, 5, 1])

kernel = 'rbf'
kernel_param = 10

print(get_kernel_values(X, X, kernel, kernel_param))
print(get_kernel_values_maybe(X, X.T, kernel, kernel_param))

# print(rbf_kernel_value(x, y, kernel_param))
# print(rbf_kernel_value_maybe(x, y, kernel_param))

[[1.00000000e+00 8.19401262e-40 7.17509597e-66]
 [8.19401262e-40 1.00000000e+00 6.71418429e-79]
 [7.17509597e-66 6.71418429e-79 1.00000000e+00]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [79]:
tu = (2, 3)
tu.__len__()

2

In [81]:
X = np.array([
    np.array([1, 2, 3, 1]),
    np.array([3, 2, 5, 0]),
    np.array([3, 1, 4, 4])
    # np.array([4, 2, 5])
])
x = np.array([1, 4, 3, 0])

x.shape.__len__()

1

In [87]:
X = np.array([
    np.array([1, 2, 3])
])
Y = np.array([
    np.array([3]),
    np.array([0]),
    np.array([7])
])
np.matmul(X, Y)

array([[24]])

In [34]:
def linear_kernel_value(u, v):
    return np.dot(u, v)

def poly_kernel_value(u, v, d):
    return (1+np.dot(u, v))**d

def rbf_kernel_value(u, v, gamma):
    return np.exp(-1*gamma*(np.dot(np.subtract(u, v), np.subtract(u, v))))
    # return np.exp(gamma*(2*np.matmul(u.T, v) - np.matmul(u.T, u) - np.matmul(v.T, v)))

def get_kernel_value(u, v, kernel, kernel_param):
    if kernel == 'linear':
        return linear_kernel_value(u, v)
    elif kernel == 'rbf':
        return rbf_kernel_value(u, v, kernel_param)
    elif kernel == 'poly':
        return poly_kernel_value(u, v, kernel_param)

def get_kernel_values(X, Y, kernel, kernel_param):
    """
    Arguments:
    X : (n,d) shape numpy array
    kernel = 'linear' or 'rbf' or 'poly'
    reg_param = lambda, for regularized logistic regression
    kernel_param = gamma for rbf kernel or degree of poly kernel

    Returns the kernel matrix :
    K: (n,n) shape numpy array
    """
    return np.array(list(np.array(list(get_kernel_value(X_i, Y_j, kernel, kernel_param) for Y_j in Y)) for X_i in X))

# def get_kernel_values(u, V, kernel, kernel_param):
#     if kernel == 'rbf':
#         return np.exp(-1*kernel_param*(
#             np.add(np.matmul(u.T, u), 
#             np.add(-2*np.matmul(u.T, V), np.sum(V**2, axis=0)))
#         ))
#     else:
#         return get_kernel_value(u, V, kernel, kernel_param)

def get_kernel_values_maybe(X, Y, kernel, kernel_param):
    """
    Arguments:
    X : (n,d) shape numpy array
    kernel = 'linear' or 'rbf' or 'poly'
    reg_param = lambda, for regularized logistic regression
    kernel_param = gamma for rbf kernel or degree of poly kernel

    Returns the kernel matrix :
    K: (n,n) shape numpy array
    """
    # return np.array(list(np.array(list(get_kernel_value(X_i, X_j, kernel, kernel_param) for X_j in X)) for X_i in X))
    if kernel == 'linear':
        return np.matmul(X, np.transpose(Y))
    elif kernel == 'poly':
        return (1 + np.matmul(X, np.transpose(Y)))**kernel_param
    elif kernel == 'rbf':
        X_norm_sq = np.sum(X**2, axis=-1)
        Y_norm_sq = np.sum(Y**2, axis=-1)
        return np.exp(-1 * kernel_param * (X_norm_sq[:, None] + Y_norm_sq[None, :] - 2*np.matmul(X, np.transpose(Y))))

# X = np.array([
#     np.array([1, 2, 3]),
#     np.array([3, 2, 5])
# ])
# Y = np.array([
#     np.array([3, 3, 1]),
#     np.array([3, 5, 1]),
#     np.array([6, -1, 3]),
#     np.array([0, 5, -1])
# ])
# X = np.array([1, 4, 2])
# Y = np.array([-4, 3, 0])

def get_kernel_matrix(X, kernel, kernel_param):
    """
    Arguments:
    X : (n,d) shape numpy array
    kernel = 'linear' or 'rbf' or 'poly'
    reg_param = lambda, for regularized logistic regression
    kernel_param = gamma for rbf kernel or degree of poly kernel

    Returns the kernel matrix :
    K: (n,n) shape numpy array
    """
    # return np.array(list(np.array(list(get_kernel_value(X_i, X_j, kernel, kernel_param) for X_j in X)) for X_i in X))
    if kernel == 'linear':
        return np.matmul(X, np.transpose(X))
    elif kernel == 'poly':
        return (1 + np.matmul(X, np.transpose(X)))**kernel_param
    elif kernel == 'rbf':
        X_norm_sq = np.sum(X**2, axis=1)
        return np.exp(-1 * kernel_param * (X_norm_sq[:, None] + X_norm_sq[None, :]- 2*np.matmul(X, np.transpose(X))))

data = np.load("Datasets/dataset_A.npz")
X = data['arr_0']
Y = data['arr_2']
kernel = 'rbf'
kernel_param = 10
# print(get_kernel_values(X, Y, kernel, kernel_param))
# print(get_kernel_values_maybe(X, Y, kernel, kernel_param))
print(np.sum(np.abs(np.subtract(get_kernel_matrix(X, kernel, kernel_param), get_kernel_values_maybe(X, X, kernel, kernel_param)))))

0.0


In [35]:
res = np.array([1, 3, 2, -4, 0, 3, -2])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]:
Y = np.array([1, 0, -1, -1, 1, 1, 0, -1, 1, 1])
def change_zero(x):
    if x == 0:
        return 1
    return x
# np.apply_along_axis(change_zero, 0, Y)
Y = np.sign(Y + 0.5)
Y

array([ 1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1.])