In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import matplotlib as mpl
import pandas as pd

In [5]:
np.load("Datasets/dataset_A.npz").files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [9]:
datasets = [np.load("Datasets/dataset_A.npz"), np.load("Datasets/dataset_B.npz"), np.load("Datasets/dataset_C.npz"), np.load("Datasets/dataset_D.npz")]
datasets[0].files
datasets[0]['arr_0']

array([[-0.72530338,  0.82268144],
       [ 0.02619935,  0.20195171],
       [ 0.68680741,  0.40459509],
       ...,
       [ 0.53226229, -0.35801377],
       [ 0.6113741 , -0.5773362 ],
       [ 0.3991032 , -0.21454145]])

In [8]:
arr = np.array([
    np.array([1, 2, 3]),
    np.array([4, 5, 6]),
    np.array([7, 8, 9])
])
arr[:,1]

array([2, 5, 8])

In [10]:
np.dot(np.transpose(np.array([1, 2, 3])), np.array([1, 2, 3]))

14

In [5]:
X = np.array([
    np.array([1, 2, 3]),
    np.array([4, 5, 6]),
    np.array([7, 8, 9]),
    np.array([10, 11, 12]),
    np.array([13, 14, 15]),
    np.array([16, 17, 18]),
    np.array([19, 20, 21]),
    np.array([22, 23, 24]),
    np.array([25, 26, 27]),
    np.array([28, 29, 30])
])
np.append(X[1:3], X[7:], axis=0)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [7]:
X[:4]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
5.1%3

2.0999999999999996

In [12]:
5.1 - 3*(5.1//3)

2.0999999999999996

In [13]:
5.1 - 3*5.1//3

0.09999999999999964

In [25]:
svclf = svm.SVC()
gamma=0.5
svclf.set_params(**{'gamma':gamma, 'degree':5})
svclf.gamma

0.5

In [24]:
svclf.degree

5

In [27]:
datasets[0]['arr_0'].shape

(1500, 2)